project:
  type: book


book:
  title: "Data Science III with python (Class notes)"
  subtitle: "STAT 303-3"
  author: "Arvind Krishna"
  date: "3/24/2023"
  
  sidebar:
    search: true
    logo: "NU_Stat_logo.png"
    logo-href: "https://statistics.northwestern.edu/"
    
  chapters:
    - index.qmd
    - part: "Sklearn; Bias & Variance; KNN"
      chapters:
        - L1_Scikit-learn.ipynb
        - Bias_variance_code.ipynb
        - KNN.ipynb
        - Hyperparameter tuning.ipynb
    - part: "Tree based models"
      chapters:
        - Lec3_RegressionTrees.ipynb
        - Lec4_ClassificationTree.ipynb
        - Lec4_Bagging.ipynb
        - Bagging (OOB vs K-fold cross-validation).ipynb
        - Lec6_RandomForest.ipynb
        - Lec7_AdaBoost.ipynb
        - Lec8_Gradient_Boosting.ipynb
        - Lec9_XGBoost.ipynb
        - Lec11_More boosting models.ipynb
        - Lec10_Ensemble.ipynb
    - part: "Assignments"
      chapters:
        - Assignment1.ipynb
        - Assignment 2 questions.ipynb
        - Assignment 3.ipynb
        - HomeworkAssignment4.ipynb
        - Assignment5_questions.ipynb

  appendices: 
    - Stratified splitting.ipynb
    - Parallel_processing_Bonus_Questions.ipynb
    - Miscellaneous questions.ipynb
    - Pipeline.ipynb
    - Datasets.ipynb

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



