project:
  type: book
  output-dir: docs


book:
  title: "Data Science III with python (Class notes)"
  subtitle: "STAT 303-3"
  author: "Lizhen Shi"
  date: "4/2/2025"
  
  sidebar:
    search: true
    logo: "NU_Stat_logo.png"
    logo-href: "https://statistics.northwestern.edu/"
    
  chapters:
    - index.qmd
    - part: "Bias & Variance; KNN"
      chapters:
        - Bias_variance_code.ipynb
        - KNN.ipynb
        - Hyperparameter tuning.ipynb
    - part: "Tree based models"
      chapters:
        - regression_tree_sp25.ipynb
        - Classification _Tree.ipynb
        - bagging.ipynb
        - Bagging (OOB vs K-fold cross-validation).ipynb
        - Lec6_RandomForest.ipynb
        - Lec7_AdaBoost.ipynb
        - Lec8_Gradient_Boosting.ipynb
        - Lec9_XGBoost.ipynb
        - Lec11_More boosting models.ipynb
        - Lec10_Ensemble.ipynb
  appendices: 
    - Assignment1_sp25.ipynb
    - Assignment2_sp25.ipynb
    - Assignment3_sp25.ipynb
    #- App_GridSearchCV_vs_RandomSearchCV.ipynb
    - Datasets.ipynb

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



