project:
  type: book


book:
  title: "Data Science III with python (Class notes)"
  subtitle: "STAT 303-3"
  author: "Arvind Krishna"
  date: "3/24/2023"
  
  sidebar:
    search: true
    logo: "NU_Stat_logo.png"
    logo-href: "https://statistics.northwestern.edu/"
    
  chapters:
    - index.qmd
    - L1_Scikit-learn.ipynb
    - Lec3_RegressionTrees.ipynb
    - Lec4_ClassificationTree.ipynb
  appendices: 
    - Stratified splitting.ipynb
    - Datasets.ipynb

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



